name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build Windows executable
        run: |
          go build -ldflags="-H windowsgui -s -w" -o moviestream-windows-amd64.exe

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: moviestream-windows-amd64
          path: moviestream-windows-amd64.exe

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./moviestream-windows-amd64.exe
          asset_name: moviestream-windows-amd64.exe
          asset_content_type: application/octet-stream

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev
          go mod download
          go mod tidy

      - name: Build Linux executable
        run: |
          go build -ldflags="-s -w" -o moviestream-linux-amd64

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: moviestream-linux-amd64
          path: moviestream-linux-amd64

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./moviestream-linux-amd64
          asset_name: moviestream-linux-amd64
          asset_content_type: application/octet-stream

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build macOS executable (Intel)
        env:
          CGO_ENABLED: 1
          GOOS: darwin
          GOARCH: amd64
        run: |
          go build -ldflags="-s -w" -o moviestream-macos-amd64

      - name: Build macOS executable (ARM64)
        env:
          CGO_ENABLED: 1
          GOOS: darwin
          GOARCH: arm64
        run: |
          go build -ldflags="-s -w" -o moviestream-macos-arm64

      - name: Upload macOS Intel artifact
        uses: actions/upload-artifact@v3
        with:
          name: moviestream-macos-amd64
          path: moviestream-macos-amd64

      - name: Upload macOS ARM64 artifact
        uses: actions/upload-artifact@v3
        with:
          name: moviestream-macos-arm64
          path: moviestream-macos-arm64

      - name: Upload macOS Intel to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./moviestream-macos-amd64
          asset_name: moviestream-macos-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS ARM64 to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./moviestream-macos-arm64
          asset_name: moviestream-macos-arm64
          asset_content_type: application/octet-stream

